version: 2
mergeable:
  - when: pull_request.*, status.*, 'issues.*'
    name: PR title, labels & description
    validate:
      - do: title
        must_exclude:
          regex: 'DO NOT MERGE|WIP'
          message: 'WIP is used in the title!'
      - do: label
        must_exclude:
          regex: 'wip'
          message: 'wip label is used.'
      - do: label
        must_exclude:
          regex: 'DO NOT MERGE'
          message: 'DO NOT MERGE label is used!'
      - do: label
        must_include:
          regex: 'QA Done'
          message: 'You need to add QA Done label!'
      - do: description
        no_empty:
          enabled: true
          message: 'PR description is empty!'
  - when: pull_request.*, status.*, 'issues.*'
    name: PR assignee check
    validate:
      - do: assignee
        min:
          count: 1
          message: 'Please select at least one assignee'
    pass:
      - do: checks
        status: 'success'
        payload:
          title: 'PR assignee looks good!'
          summary: 'All assignee checks passed'
    fail:
      - do: assign
        assignees: [ '@author' ]
  - when: pull_request.*, pull_request_review.*, status.*, check_suite.*
    name: "Automatically merge pull requests once it passes all checks"
    validate: []
    pass:
      - do: merge
        merge_method: "squash"
        commit_title: '{{{ title }}} (#{{{ number }}})' # Optional, override commit title
